version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./backend:/app
      - ./server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
  php:
    image: amauryfaveriel/php-fpm
    volumes:
      - ./backend:/app
    networks:
      - backend
  database:
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    networks: 
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heticchallenge
      MYSQL_USER: hetic
      MYSQL_PASSWORD: hetic
    ports:
      - 3307:3306

networks: 
  backend: